// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schemas/greeter/greeter.proto

package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/qeelyn/go-common/protobuf/timestamp"
import _ "github.com/qeelyn/go-common/protobuf/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" `
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_b3620ec79b573599, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" `
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty" `
	// @inject_tag: json:"start_date"
	Date                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date" json:"start_date"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" gorm:"-"`
	XXX_unrecognized     []byte               `json:"-" gorm:"-"`
	XXX_sizecache        int32                `json:"-" gorm:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_b3620ec79b573599, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Greeter/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	Hello(context.Context, *Request) (*Response, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Greeter_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schemas/greeter/greeter.proto",
}

func init() {
	proto.RegisterFile("schemas/greeter/greeter.proto", fileDescriptor_greeter_b3620ec79b573599)
}

var fileDescriptor_greeter_b3620ec79b573599 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x4f, 0x87, 0x30,
	0x10, 0xc5, 0x03, 0x7f, 0x14, 0x38, 0x13, 0x63, 0x3a, 0x11, 0x22, 0x4a, 0x58, 0x64, 0x2a, 0x09,
	0x7e, 0x08, 0x9d, 0x1b, 0x47, 0x97, 0x22, 0x67, 0x25, 0xa1, 0xb4, 0xf6, 0x4a, 0xfc, 0xfa, 0xc6,
	0x42, 0x17, 0xa7, 0xbe, 0xde, 0x7b, 0xb9, 0xdf, 0x3b, 0x68, 0xe8, 0xe3, 0x0b, 0xb5, 0xa4, 0x41,
	0x39, 0x44, 0x8f, 0x2e, 0xbe, 0xdc, 0x3a, 0xe3, 0x4d, 0xfd, 0xa8, 0x8c, 0x51, 0x2b, 0x0e, 0xe1,
	0x37, 0xed, 0x9f, 0x83, 0x5f, 0x34, 0x92, 0x97, 0xda, 0x9e, 0x81, 0x87, 0xff, 0x81, 0x1f, 0x27,
	0xad, 0x45, 0x47, 0x87, 0xdf, 0x35, 0x90, 0x0b, 0xfc, 0xde, 0x91, 0x3c, 0x63, 0x90, 0x6d, 0x52,
	0x63, 0x95, 0xb4, 0x49, 0x5f, 0x8a, 0xa0, 0xbb, 0x77, 0x28, 0x04, 0x92, 0x35, 0x1b, 0x21, 0xbb,
	0x85, 0x74, 0x99, 0x4f, 0x37, 0x5d, 0x66, 0x76, 0x07, 0x17, 0x4d, 0xaa, 0x4a, 0xc3, 0xe0, 0x4f,
	0x32, 0x0e, 0xd9, 0x2c, 0x3d, 0x56, 0x97, 0x36, 0xe9, 0x6f, 0xc6, 0x9a, 0x1f, 0x6c, 0x1e, 0xd9,
	0xfc, 0x2d, 0x96, 0x13, 0x21, 0x37, 0x3e, 0x41, 0xfe, 0x72, 0x9c, 0xc3, 0xee, 0xe1, 0xea, 0x15,
	0xd7, 0xd5, 0xb0, 0x82, 0x9f, 0x7d, 0xea, 0x92, 0x47, 0xf4, 0x74, 0x1d, 0x56, 0x3c, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x04, 0x65, 0xea, 0x31, 0x0e, 0x01, 0x00, 0x00,
}
